name: Configuration Imprimante Service
description: Séquence pour configurer une imprimante de service avec paramètres standards

plugins:
  - name: add_printer
    template: imprimante_service
    conditions:
      - variable: SYSTEM_STATUS
        operator: '=='
        value: true
