# Configuration des fonctionnalités de pcUtils
sequence_manager:
  enabled: true
  default_dir: "sequences"

templates:
  enabled: true
  show_select_if_empty: false
  auto_select_default: true

report_generator:
  enabled: true
  generate_by_default: true
  format: "csv"

auto_mode:
  enabled: true
  save_reports: true
  collect_remote_reports: true

display:
  auto_compact: true
  min_compact_width: 80
  min_compact_height: 24

keybindings:
  enabled: true
  config_file: "config/keybindings.yml"

checkpoints:
  enabled: true
  auto_resume: true
  checkpoint_dir: "checkpoints"