# Configuration des raccourcis clavier pour pcUtils
global:
  quit: "q"
  help: "F1"
  toggle_logs: "l"

plugin_selection:
  select_all: "a"
  deselect_all: "d"
  search: "/"

configuration:
  next_field: "tab"
  previous_field: "shift+tab"
  toggle_advanced: "a"

execution:
  pause: "p"
  abort: "ctrl+c"
  toggle_report: "r"